"""empty message

Revision ID: 13a3fa219484
Revises: 24738de3d9b4
Create Date: 2016-10-23 00:30:37.439000

"""

# revision identifiers, used by Alembic.
revision = '13a3fa219484'
down_revision = '24738de3d9b4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
