"""empty message

Revision ID: 1a81df8d68f3
Revises: 1e8fa97d06e4
Create Date: 2016-10-23 00:36:49.833000

"""

# revision identifiers, used by Alembic.
revision = '1a81df8d68f3'
down_revision = '1e8fa97d06e4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
