"""empty message

Revision ID: 1e8fa97d06e4
Revises: 13a3fa219484
Create Date: 2016-10-23 00:33:05.817000

"""

# revision identifiers, used by Alembic.
revision = '1e8fa97d06e4'
down_revision = '13a3fa219484'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
