"""empty message

Revision ID: 213ee1e94b49
Revises: 4b6a94b5b998
Create Date: 2016-10-22 23:53:36.793000

"""

# revision identifiers, used by Alembic.
revision = '213ee1e94b49'
down_revision = '4b6a94b5b998'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
