"""empty message

Revision ID: 24738de3d9b4
Revises: 2a0f28a6ce64
Create Date: 2016-10-23 00:05:22.897000

"""

# revision identifiers, used by Alembic.
revision = '24738de3d9b4'
down_revision = '2a0f28a6ce64'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
