"""empty message

Revision ID: 2a0f28a6ce64
Revises: 213ee1e94b49
Create Date: 2016-10-23 00:03:20.576000

"""

# revision identifiers, used by Alembic.
revision = '2a0f28a6ce64'
down_revision = '213ee1e94b49'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
