"""empty message

Revision ID: 2a3a94bb7716
Revises: 1a81df8d68f3
Create Date: 2016-10-23 00:42:58.733000

"""

# revision identifiers, used by Alembic.
revision = '2a3a94bb7716'
down_revision = '1a81df8d68f3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
