"""empty message

Revision ID: 2d9cf26fbfb0
Revises: 41fa89481b7
Create Date: 2016-10-23 12:10:39.685000

"""

# revision identifiers, used by Alembic.
revision = '2d9cf26fbfb0'
down_revision = '41fa89481b7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
