"""empty message

Revision ID: 3657b8de770
Revises: 2d9cf26fbfb0
Create Date: 2016-10-23 18:12:08.882000

"""

# revision identifiers, used by Alembic.
revision = '3657b8de770'
down_revision = '2d9cf26fbfb0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
