"""empty message

Revision ID: 38cb8dbef73
Revises: 3657b8de770
Create Date: 2016-10-23 18:18:46.675000

"""

# revision identifiers, used by Alembic.
revision = '38cb8dbef73'
down_revision = '3657b8de770'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
