"""empty message

Revision ID: 3a7e1ef8a1c5
Revises: 49fe1c6df959
Create Date: 2016-10-23 01:01:59.216000

"""

# revision identifiers, used by Alembic.
revision = '3a7e1ef8a1c5'
down_revision = '49fe1c6df959'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
