"""empty message

Revision ID: 41fa89481b7
Revises: 5bd1fe59e8b
Create Date: 2016-10-23 11:57:40.954000

"""

# revision identifiers, used by Alembic.
revision = '41fa89481b7'
down_revision = '5bd1fe59e8b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
