"""empty message

Revision ID: 4cb48ccdd900
Revises: 38cb8dbef73
Create Date: 2016-10-23 18:26:40.876000

"""

# revision identifiers, used by Alembic.
revision = '4cb48ccdd900'
down_revision = '38cb8dbef73'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
