"""empty message

Revision ID: 8ad1e0faad5
Revises: 2a3a94bb7716
Create Date: 2016-10-23 00:44:12.671000

"""

# revision identifiers, used by Alembic.
revision = '8ad1e0faad5'
down_revision = '2a3a94bb7716'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
